-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS products.models
(
    model_id serial NOT NULL,
    model_name text NOT NULL,
    brand_id_fk smallint NOT NULL,
    PRIMARY KEY (model_id),
    UNIQUE (model_name)
);

CREATE TABLE IF NOT EXISTS products.brands
(
    brand_id serial NOT NULL,
    brand_name text NOT NULL,
    origin smallint NOT NULL,
    PRIMARY KEY (brand_id),
    UNIQUE (brand_name)
);

CREATE TABLE IF NOT EXISTS products.attribute_keys
(
    attribute_key_id serial NOT NULL,
    attribute_key_name text NOT NULL,
    description text,
    PRIMARY KEY (attribute_key_id),
    UNIQUE (attribute_key_name)
);

CREATE TABLE IF NOT EXISTS products.attribute_values
(
    attribute_value_id serial NOT NULL,
    attribute_value_name text NOT NULL,
    description text,
    attribute_key_id_fk integer NOT NULL,
    PRIMARY KEY (attribute_value_id)
);

CREATE TABLE IF NOT EXISTS products.version_attributes
(
    version_attribute_id serial NOT NULL,
    version_id_fk integer NOT NULL,
    attribute_value_id_fk integer NOT NULL,
    PRIMARY KEY (version_attribute_id)
);

CREATE TABLE IF NOT EXISTS products.versions
(
    version_id serial NOT NULL,
    version_name text NOT NULL,
    model_id_fk integer NOT NULL,
    model_year integer NOT NULL,
    PRIMARY KEY (version_id)
);

ALTER TABLE IF EXISTS products.models
    ADD FOREIGN KEY (brand_id_fk)
    REFERENCES products.brands (brand_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS products.attribute_values
    ADD FOREIGN KEY (attribute_key_id_fk)
    REFERENCES products.attribute_keys (attribute_key_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS products.version_attributes
    ADD FOREIGN KEY (attribute_value_id_fk)
    REFERENCES products.attribute_values (attribute_value_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS products.version_attributes
    ADD FOREIGN KEY (version_id_fk)
    REFERENCES products.versions (version_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS products.versions
    ADD FOREIGN KEY (model_id_fk)
    REFERENCES products.models (model_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;

END;
